#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Sep 20 16:52:38 MSK 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 4e45d21053af4d51b6e5c73de3d1b64e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot MII_TX_PKT_tb_behav xil_defaultlib.MII_TX_PKT_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto 4e45d21053af4d51b6e5c73de3d1b64e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot MII_TX_PKT_tb_behav xil_defaultlib.MII_TX_PKT_tb xil_defaultlib.glbl -log elaborate.log

