#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Sep 20 16:53:04 MSK 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim MII_TX_PKT_tb_behav -key {Behavioral:sim_1:Functional:MII_TX_PKT_tb} -tclbatch MII_TX_PKT_tb.tcl -view /home/master/FPGA_proj/canda_vhdl/tx_25701_tb_behav.wcfg -log simulate.log"
xsim MII_TX_PKT_tb_behav -key {Behavioral:sim_1:Functional:MII_TX_PKT_tb} -tclbatch MII_TX_PKT_tb.tcl -view /home/master/FPGA_proj/canda_vhdl/tx_25701_tb_behav.wcfg -log simulate.log

