webtalk_init -webtalk_dir /home/master/FPGA_proj/canda_vhdl/canda_vhdl.sim/sim_1/behav/xsim/xsim.dir/tx_25701_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun May 16 12:51:39 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "81a89879533253b4b48f0d83de28881a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4e45d21053af4d51b6e5c73de3d1b64e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "17" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2430.808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "30 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "3.11_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "126020_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1864538173 -regid "" -xml /home/master/FPGA_proj/canda_vhdl/canda_vhdl.sim/sim_1/behav/xsim/xsim.dir/tx_25701_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/master/FPGA_proj/canda_vhdl/canda_vhdl.sim/sim_1/behav/xsim/xsim.dir/tx_25701_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/master/FPGA_proj/canda_vhdl/canda_vhdl.sim/sim_1/behav/xsim/xsim.dir/tx_25701_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
