# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/master/FPGA_proj/CANDA_SPI_SO_FD/canda_spiso_fd.srcs/sources_1/ip/fifo2_4k/fifo2_4k.xci
# IP: The module: 'fifo2_4k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/master/FPGA_proj/CANDA_SPI_SO_FD/canda_vhdl.gen/sources_1/ip/fifo2_4k/fifo2_4k.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo2_4k'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/master/FPGA_proj/CANDA_SPI_SO_FD/canda_vhdl.gen/sources_1/ip/fifo2_4k/fifo2_4k_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo2_4k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/master/FPGA_proj/CANDA_SPI_SO_FD/canda_vhdl.gen/sources_1/ip/fifo2_4k/fifo2_4k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo2_4k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/master/FPGA_proj/CANDA_SPI_SO_FD/canda_spiso_fd.srcs/sources_1/ip/fifo2_4k/fifo2_4k.xci
# IP: The module: 'fifo2_4k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/master/FPGA_proj/CANDA_SPI_SO_FD/canda_vhdl.gen/sources_1/ip/fifo2_4k/fifo2_4k.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo2_4k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/master/FPGA_proj/CANDA_SPI_SO_FD/canda_vhdl.gen/sources_1/ip/fifo2_4k/fifo2_4k_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo2_4k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/master/FPGA_proj/CANDA_SPI_SO_FD/canda_vhdl.gen/sources_1/ip/fifo2_4k/fifo2_4k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo2_4k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
